### ISSUE TITLE
Options.style not works

### ISSUE THREAD

**Issue by Yaroslav-Pryadunov** [dievardump/yasp-modals#3]
```
<Modals options={{
	close: {
		showBtn: false
	},
	style: `
		position: fixed;
		top: 0;
		left: 0;
		width: 100%;
		height: 100%;
		z-index: 100;
		background-color: rgba(0, 0, 0, .5);
		display: flex;
		flex-direction: column;
	`
}}/>
```
The redefined style is not applied to the wrapper.

**Comment by dievardump** [comment]
Oh I'm sorry, this is a Documentation error.

Properties to add directly to the Modals wrapper should be in options.props (as in element properties), so here it should be:


```
<Modals options={{
	close: {
		showBtn: false
	},
	props: {
		style: `
			position: fixed;
			top: 0;
			left: 0;
			width: 100%;
			height: 100%;
			z-index: 100;
			background-color: rgba(0, 0, 0, .5);
			display: flex;
			flex-direction: column;
		`
	}
}}/>
```

**Comment by dievardump** [comment]
Actually the code seems to not follow this neither. I will update this right now, sorry for that

**Comment by dievardump** [comment]
I just pushed a new version on npm.

https://github.com/dievardump/yasp-modals/blob/0b8da8a49b431671d2abf4966ea6044628cfbd13/src/components/Modals.svelte#L104

this should have fixed it.
